"""
Django settings for blog_back project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# 构建项目内部路径，例如：BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 开发环境SECRET_KEY，生产环境将由set_prod.py覆盖
SECRET_KEY = 'DJANGO_SECRET_KEY'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

ALLOWED_HOSTS = ["*"]# 允许所有域名


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173"
]

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.contenttypes',  # 验证码需要
    'django.contrib.sessions',      # 会话管理
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',                      # 验证码
    'common',
    'home',
    'register',
    'forgot',
    'login',
    'article',                      # 文章应用
    'network_disk',                # 网盘应用
    'history',                      # 更新历史应用
    'feedback',                     # 反馈应用
]
#允许指定域名跨域，开发环境需要，生产环境使用nginx代理，可以不配置
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173"
]
#允许携带cookie
CORS_ALLOW_CREDENTIALS = True
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'common.middleware.LoginLimitMiddleware',
    'common.jwt_middleware.JWTAuthenticationMiddleware',  # JWT认证中间件
    'common.jwt_middleware.JWTAuthRequiredMiddleware',    # JWT强制认证中间件
]

ROOT_URLCONF = 'blog_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'webproject',
#         'USER': 'root',
#         'PASSWORD': '123456',#生产环境建议修改密码
#         'HOST': '127.0.0.1',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'api/static/'
STATICFILES_DIRS = [
    BASE_DIR / "api/static"
]

# 媒体文件配置（用于验证码图片）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 验证码配置（从配置文件读取）
try:
    from common.config_utils import load_config
    captcha_config = load_config().get('captcha', {})
    CAPTCHA_CHALLENGE_FUNCT = captcha_config.get('challenge_funct', 'captcha.helpers.random_char_challenge')
    CAPTCHA_LENGTH = captcha_config.get('length', 4)
    CAPTCHA_TIMEOUT = captcha_config.get('timeout', 5)  # 验证码有效期（分钟）
    CAPTCHA_IMAGE_SIZE = tuple(captcha_config.get('image_size', [120, 40]))
    CAPTCHA_FONT_SIZE = captcha_config.get('font_size', 20)
    CAPTCHA_BACKGROUND_COLOR = captcha_config.get('background_color', '#ffffff')
    CAPTCHA_FOREGROUND_COLOR = captcha_config.get('foreground_color', '#001100')
    CAPTCHA_NOISE_FUNCTIONS = tuple(captcha_config.get('noise_functions', ['captcha.helpers.noise_arcs', 'captcha.helpers.noise_dots']))
except Exception:
    # 如果读取配置失败，使用默认值
    CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'
    CAPTCHA_LENGTH = 4
    CAPTCHA_TIMEOUT = 5
    CAPTCHA_IMAGE_SIZE = (120, 40)
    CAPTCHA_FONT_SIZE = 20
    CAPTCHA_BACKGROUND_COLOR = '#ffffff'
    CAPTCHA_FOREGROUND_COLOR = '#001100'
    CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs', 'captcha.helpers.noise_dots',)

#配置环境检测
CURRENT_ENV = 'dev'#实际运行时根据环境修改
if CURRENT_ENV == 'dev':
    from .set_dev import *
elif CURRENT_ENV == 'prod':
    from .set_prod import *
# 会话设置
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
