/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Article_main: typeof import('./src/components/article_main.vue')['default']
    CaptchaDialog: typeof import('./src/components/CaptchaDialog.vue')['default']
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    CreateButton: typeof import('./src/components/CreateButton.vue')['default']
    FeedbackButton: typeof import('./src/components/FeedbackButton.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FullScreenLoading: typeof import('./src/components/FullScreenLoading.vue')['default']
    Head: typeof import('./src/components/Head.vue')['default']
    Home_main: typeof import('./src/components/home_main.vue')['default']
    Logout: typeof import('./src/components/Logout.vue')['default']
    Network_disk_main: typeof import('./src/components/network_disk_main.vue')['default']
    Page_number: typeof import('./src/components/page_number.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/theme.vue')['default']
    User_home_edit: typeof import('./src/components/user_home_edit.vue')['default']
    User_home_main: typeof import('./src/components/user_home_main.vue')['default']
    UserInfoSidebar: typeof import('./src/components/UserInfoSidebar.vue')['default']
    Write_main: typeof import('./src/components/write_main.vue')['default']
  }
}
