/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaptchaDialog: typeof import('./src/components/CaptchaDialog.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FullScreenLoading: typeof import('./src/components/FullScreenLoading.vue')['default']
    Head: typeof import('./src/components/Head.vue')['default']
    Home_main: typeof import('./src/components/home_main.vue')['default']
    Logout: typeof import('./src/components/Logout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme: typeof import('./src/components/theme.vue')['default']
  }
}
